set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

# Use cross sysroot if available
execute_process(
  COMMAND aarch64-linux-gnu-g++ -print-sysroot
  OUTPUT_VARIABLE _SYSROOT
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(_SYSROOT)
  set(CMAKE_SYSROOT "${_SYSROOT}")
  set(CMAKE_FIND_ROOT_PATH "${_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
